export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const REMOVE_AUTH_ERROR = "REMOVE_AUTH_ERROR";
export const LOG_OUT = "LOG_OUT";

export const AVATAR_SUCCESS = "AVATAR_SUCCESS";
export const AVATAR_FAIL = "AVATAR_FAIL";

export const NAME_SUCCESS = "NAME_SUCCESS";
export const NAME_FAIL = "NAME_FAIL";

export const ADDRESS_SUCCESS = "ADDRESS_SUCCESS";
export const ADDRESS_FAIL = "ADDRESS_FAIL";

export const PRONUMBER_SUCCESS = "PRONUMBER_SUCCESS";
export const PRONUMBER_FAIL = "PRONUMBER_FAIL";

export const FACEBOOK_SUCCESS = "FACEBOOK_SUCCESS";
export const FACEBOOK_FAIL = "FACEBOOK_FAIL";

export const TWITTER_SUCCESS = "TWITTER_SUCCESS";
export const TWITTER_FAIL = "TWITTER_FAIL";

export const INSTAGRAM_SUCCESS = "INSTAGRAM_SUCCESS";
export const INSTAGRAM_FAIL = "INSTAGRAM_FAIL";

export const YOUTUBE_SUCCESS = "YOUTUBE_SUCCESS";
export const YOUTUBE_FAIL = "YOUTUBE_FAIL";

export const PHONE_SUCCESS = "PHONE_SUCCESS";
export const PHONE_FAIL = "PHONE_FAIL";

export const PASSWORD_SUCCESS = "PASSWORD_SUCCESS";
export const PASSWORD_FAIL = "PASSWORD_FAIL";

export const GALLERY_SUCCESS = "GALLERY_SUCCESS";
export const GALLERY_FAIL = "GALLERY_FAIL";

export const LOAD_GALLERY_SUCCESS = "LOAD_GALLERY_SUCCESS";
export const LOAD_GALLERY_FAIL = "LOAD_GALLERY_FAIL";

export const DELETE_GALLERY_SUCCESS = "DELETE_GALLERY_SUCCESS";
export const DELETE_GALLERY_FAIL = "DELETE_GALLERY_FAIL";

export const OFFER_SUCCESS = "OFFER_SUCCESS";
export const OFFER_FAIL = "OFFER_FAIL";

export const LOAD_OFFER_SUCCESS = "LOAD_OFFER_SUCCESS";
export const LOAD_OFFER_FAIL = "LOAD_OFFER_FAIL";

export const DELETE_OFFER_SUCCESS = "DELETE_OFFER_SUCCESS";
export const DELETE_OFFER_FAIL = "DELETE_OFFER_FAIL";

export const TESTIMONIAL_SUCCESS = "TESTIMONIAL_SUCCESS";
export const TESTIMONIAL_FAIL = "TESTIMONIAL_FAIL";

export const LOAD_TESTIMONIAL_SUCCESS = "LOAD_TESTIMONIAL_SUCCESS";
export const LOAD_TESTIMONIAL_FAIL = "LOAD_TESTIMONIAL_FAIL";

export const CONTACT_SUCCESS = "CONTACT_SUCCESS";
export const CONTACT_FAIL = "CONTACT_FAIL";

export const WEDDING_INVITATION_SUCCESS = "WEDDING_INVITATION_SUCCESS";
export const WEDDING_INVITATION_FAIL = "WEDDING_INVITATION_FAIL";

export const WEDDING_VENUE_SUCCESS = "WEDDING_VENUE_SUCCESS";
export const WEDDING_VENUE_FAIL = "WEDDING_VENUE_FAIL";

export const HAIR_STYLIST_SUCCESS = "HAIR_STYLIST_SUCCESS";
export const HAIR_STYLIST_FAIL = "HAIR_STYLIST_FAIL";

export const PHOTOGRAPHER_SUCCESS = "PHOTOGRAPHER_SUCCESS";
export const PHOTOGRAPHER_FAIL = "PHOTOGRAPHER_FAIL";

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const RATING_SUCCESS = "RATING_SUCCESS";
export const RATING_FAIL = "RATING_FAIL";

export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_FAIL = "COMMENT_FAIL";

export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAIL = "UPDATE_COMMENT_FAIL";

export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

export const REPLY_SUCCESS = "REPLY_SUCCESS";
export const REPLY_FAIL = "REPLY_FAIL";

export const UPDATE_REPLY_SUCCESS = "UPDATE_REPLY_SUCCESS";
export const UPDATE_REPLY_FAIL = "UPDATE_REPLY_FAIL";

export const DELETE_REPLY_SUCCESS = "DELETE_REPLY_SUCCESS";
export const DELETE_REPLY_FAIL = "DELETE_REPLY_FAIL";

export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL";

export const REMOVE = "REMOVE";
